### PR TITLE
remove bogus language

### PR DESCRIPTION
**Pull request by ulferts**

### CODE REVIEW

**Comment by tessi** [comment]
Don't we use inline crowdin translations anymore?

**Comment by tessi** [comment]
@ulferts the actual feature name is in-context translation (https://crowdin.com/page/in-context-localization). I really like that feature and would love to advertise it more instead of removing it.

Can you tell me why this is to be removed?

**Comment by ulferts** [comment]
@tessi it was due to lack of understanding on my side. That file struck me as weird (especially the locale description "lol") so I thought someone added a bogus locale.

**Comment by tessi** [comment]
Ah, I see. The thing is: You need to have an existing locale to put the in-context translation symbols into. Instead of choosing a widely used locale, I choose a locale which we might not need (lolcat language).

The other candidate was pirate-english, but I might want to translate OpenProject into pirate some day ;)

**Comment by 0xF013** [comment]
yarrr

**Comment by myabc** [comment]
I see

**Pull request closed without merging**
